version: "3.9"
services:
  notebook:
    container_name: jupyter
    restart: always
    build: ./jupyter
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/notebooks:/notebooks
      - ./jupyter/dataset:/dataset
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root